/**
 * Ed25519 public key for license verification (DER, base64).
 *
 * This is NOT a secret - it's the public half of the signing keypair.
 * Anyone can verify signatures, but only the licensing server can create them.
 *
 * Generated by: apps/licensing/scripts/generate-keypair.ts
 */
export const LICENSING_PUBLIC_KEY = "MCowBQYDK2VwAyEAOUdzWrEw0sWnmZrceBGvH2CqHhjMPALDRAPD2jfoBxg=";
