/**
 * Ed25519 public key for license verification (DER, base64).
 *
 * This is NOT a secret - it's the public half of the signing keypair.
 * Anyone can verify signatures, but only the licensing server can create them.
 *
 * Generated by: apps/licensing/scripts/generate-keypair.ts
 */
const CANONICAL_PUBLIC_KEY = "MCowBQYDK2VwAyEAfTWdd1TDpuMILwyGax7M5Q2kt4bmXPBgmZIqR2+OQ3I=";

// Dev-only override: lets a local licensing server sign with a throwaway keypair without shipping the
// canonical private key to dev machines or touching the committed key above. Ignored outside dev, where
// instances always verify against the canonical key. APP_ENV defaults to "dev" when unset (cf config.ts).
const isDev = (process.env.APP_ENV ?? "dev") === "dev";

export const LICENSING_PUBLIC_KEY = (isDev && process.env.LICENSING_DEV_PUBLIC_KEY) || CANONICAL_PUBLIC_KEY;
