-- AlterEnum
ALTER TYPE "AuditAction" ADD VALUE 'ROOT_LICENSE_ADMIN_CREATE';
ALTER TYPE "AuditAction" ADD VALUE 'ROOT_LICENSE_ADMIN_REVOKE';
ALTER TYPE "AuditAction" ADD VALUE 'ROOT_LICENSE_ADMIN_RENEW';
