-- Add billing-related audit actions
ALTER TYPE "AuditAction" ADD VALUE 'ORG_CHECKOUT_CREATED';
ALTER TYPE "AuditAction" ADD VALUE 'ORG_SUBSCRIPTION_CREATED';
ALTER TYPE "AuditAction" ADD VALUE 'ORG_SUBSCRIPTION_CANCELLED';
ALTER TYPE "AuditAction" ADD VALUE 'ORG_SUBSCRIPTION_UPDATED';
ALTER TYPE "AuditAction" ADD VALUE 'ORG_PORTAL_SESSION_CREATED';
ALTER TYPE "AuditAction" ADD VALUE 'ORG_PAYW_UPDATED';
