import { type IApiKeyRepo } from "./IApiKeyRepo";
import { type IAppSettingsRepo } from "./IAppSettingsRepo";
import { type IAuditLogRepo } from "./IAuditLogRepo";
import { type IBoardRepo } from "./IBoardRepo";
import { type ICommentRepo } from "./ICommentRepo";
import { type IFollowRepo } from "./IFollowRepo";
import { type IIntegrationMappingRepo } from "./IIntegrationMappingRepo";
import { type IIntegrationRepo } from "./IIntegrationRepo";
import { type IIntegrationSyncLogRepo } from "./IIntegrationSyncLogRepo";
import { type IInvitationRepo } from "./IInvitationRepo";
import { type ILikeRepo } from "./ILikeRepo";
import { ApiKeyRepoPrisma } from "./impl/ApiKeyRepoPrisma";
import { AppSettingsRepoPrisma } from "./impl/AppSettingsRepoPrisma";
import { AuditLogRepoPrisma } from "./impl/AuditLogRepoPrisma";
import { BoardRepoPrisma } from "./impl/BoardRepoPrisma";
import { CommentRepoPrisma } from "./impl/CommentRepoPrisma";
import { FollowRepoPrisma } from "./impl/FollowRepoPrisma";
import { IntegrationMappingRepoPrisma } from "./impl/IntegrationMappingRepoPrisma";
import { IntegrationRepoPrisma } from "./impl/IntegrationRepoPrisma";
import { IntegrationSyncLogRepoPrisma } from "./impl/IntegrationSyncLogRepoPrisma";
import { InvitationRepoPrisma } from "./impl/InvitationRepoPrisma";
import { LikeRepoPrisma } from "./impl/LikeRepoPrisma";
import { OAuthRepoPrisma } from "./impl/OAuthRepoPrisma";
import { OrgAddonRepoPrisma } from "./impl/OrgAddonRepoPrisma";
import { OrganizationRepoPrisma } from "./impl/OrganizationRepoPrisma";
import { OrgDomainRepoPrisma } from "./impl/OrgDomainRepoPrisma";
import { OrgMemberRepoPrisma } from "./impl/OrgMemberRepoPrisma";
import { PostRepoPrisma } from "./impl/PostRepoPrisma";
import { PostStatusChangeRepoPrisma } from "./impl/PostStatusChangeRepoPrisma";
import { PostStatusRepoPrisma } from "./impl/PostStatusRepoPrisma";
import { TenantDefaultOAuthRepoPrisma } from "./impl/TenantDefaultOAuthRepoPrisma";
import { TenantRepoPrisma } from "./impl/TenantRepoPrisma";
import { TenantSettingsRepoPrisma } from "./impl/TenantSettingsRepoPrisma";
import { UserOnTenantRepoPrisma } from "./impl/UserOnTenantRepoPrisma";
import { UserRepoPrisma } from "./impl/UserRepoPrisma";
import { WebhookRepoPrisma } from "./impl/WebhookRepoPrisma";
import { type IOAuthRepo } from "./IOAuthRepo";
import { type IOrgAddonRepo } from "./IOrgAddonRepo";
import { type IOrganizationRepo } from "./IOrganizationRepo";
import { type IOrgDomainRepo } from "./IOrgDomainRepo";
import { type IOrgMemberRepo } from "./IOrgMemberRepo";
import { type IPostRepo } from "./IPostRepo";
import { type IPostStatusChangeRepo } from "./IPostStatusChangeRepo";
import { type IPostStatusRepo } from "./IPostStatusRepo";
import { type ITenantDefaultOAuthRepo } from "./ITenantDefaultOAuthRepo";
import { type ITenantRepo } from "./ITenantRepo";
import { type ITenantSettingsRepo } from "./ITenantSettingsRepo";
import { type IUserOnTenantRepo } from "./IUserOnTenantRepo";
import { type IUserRepo } from "./IUserRepo";
import { type IWebhookRepo } from "./IWebhookRepo";

export const appSettingsRepo: IAppSettingsRepo = new AppSettingsRepoPrisma();
export const auditLogRepo: IAuditLogRepo = new AuditLogRepoPrisma();
export const postRepo: IPostRepo = new PostRepoPrisma();
export const boardRepo: IBoardRepo = new BoardRepoPrisma();
export const userRepo: IUserRepo = new UserRepoPrisma();
export const commentRepo: ICommentRepo = new CommentRepoPrisma();
export const likeRepo: ILikeRepo = new LikeRepoPrisma();
export const followRepo: IFollowRepo = new FollowRepoPrisma();
export const postStatusRepo: IPostStatusRepo = new PostStatusRepoPrisma();
export const postStatusChangeRepo: IPostStatusChangeRepo = new PostStatusChangeRepoPrisma();
export const tenantRepo: ITenantRepo = new TenantRepoPrisma();
export const invitationRepo: IInvitationRepo = new InvitationRepoPrisma();
export const apiKeyRepo: IApiKeyRepo = new ApiKeyRepoPrisma();
export const oAuthRepo: IOAuthRepo = new OAuthRepoPrisma();
export const tenantSettingsRepo: ITenantSettingsRepo = new TenantSettingsRepoPrisma();
export const tenantDefaultOAuthRepo: ITenantDefaultOAuthRepo = new TenantDefaultOAuthRepoPrisma();
export const webhookRepo: IWebhookRepo = new WebhookRepoPrisma();
export const userOnTenantRepo: IUserOnTenantRepo = new UserOnTenantRepoPrisma();
export const integrationRepo: IIntegrationRepo = new IntegrationRepoPrisma();
export const integrationMappingRepo: IIntegrationMappingRepo = new IntegrationMappingRepoPrisma();
export const integrationSyncLogRepo: IIntegrationSyncLogRepo = new IntegrationSyncLogRepoPrisma();
export const organizationRepo: IOrganizationRepo = new OrganizationRepoPrisma();
export const orgMemberRepo: IOrgMemberRepo = new OrgMemberRepoPrisma();
export const orgDomainRepo: IOrgDomainRepo = new OrgDomainRepoPrisma();
export const orgAddonRepo: IOrgAddonRepo = new OrgAddonRepoPrisma();
