import { Badge } from "@roadmaps-faciles/ui";
import { getTranslations } from "next-intl/server";

import { CopyButton } from "@/components/CopyButton";
import { getOrCreateInstanceId, isInstanceIdFromEnv } from "@/lib/ee/licensing/instanceId";
import { type LicenseStatus } from "@/lib/ee/licensing/types";

const LicenseInfoRow = ({ label, value }: { label: string; value: React.ReactNode }) => (
  <div className="flex items-center justify-between border-b py-3 last:border-b-0">
    <span className="text-sm font-medium text-muted-foreground">{label}</span>
    <span className="text-sm font-semibold">{value}</span>
  </div>
);

export const StatusInfoCard = async ({ status, isCloud }: { isCloud: boolean; status: LicenseStatus }) => {
  const t = await getTranslations("rootAdmin.licensing");
  const instanceId = !isCloud ? await getOrCreateInstanceId() : null;
  // eslint-disable-next-line react-hooks/purity -- async RSC, Date.now() is fine here
  const now = Date.now();

  const modeLabel = isCloud ? t("modeCloud") : status.mode === "licensed" ? t("modeLicensed") : t("modeCommunity");

  const planLabel =
    status.plan === "GOV_LICENSED" ? t("planGovLicensed") : status.plan === "LICENSED" ? t("planLicensed") : "-";

  const statusBadge = (() => {
    if (isCloud) return <Badge variant="secondary">{t("modeCloud")}</Badge>;
    if (status.mode === "community")
      return status.reason === "invalid" ? (
        <Badge variant="destructive">{t("statusInvalidKey")}</Badge>
      ) : (
        <Badge variant="outline">{t("statusNotConfigured")}</Badge>
      );
    if (!status.valid) return <Badge variant="destructive">{t("statusExpired")}</Badge>;
    if (status.gracePeriodEnd) return <Badge variant="outline">{t("statusGracePeriod")}</Badge>;
    if (status.mode === "licensed") return <Badge className="bg-green-600 text-white">{t("statusActive")}</Badge>;
    return <Badge variant="secondary">{t("modeCommunity")}</Badge>;
  })();

  const formatDate = (date: Date | undefined) => {
    if (!date) return "-";
    return date.toLocaleDateString("fr-FR", { year: "numeric", month: "long", day: "numeric" });
  };

  const daysUntil = (date: Date | undefined) => {
    if (!date) return null;
    const diff = Math.ceil((date.getTime() - now) / (1000 * 60 * 60 * 24));
    if (diff < 0) return t("expired");
    return t("daysRemaining", { count: diff });
  };

  return (
    <div className="max-w-lg rounded-lg border p-6">
      <LicenseInfoRow label={t("mode")} value={modeLabel} />
      <LicenseInfoRow label={t("status")} value={statusBadge} />

      {!isCloud && status.mode === "licensed" && (
        <>
          <LicenseInfoRow label={t("plan")} value={planLabel} />
          <LicenseInfoRow
            label={t("expiry")}
            value={
              <span className="flex items-center gap-2">
                {formatDate(status.expiresAt)}
                {daysUntil(status.expiresAt) && (
                  <span className="text-xs text-muted-foreground">({daysUntil(status.expiresAt)})</span>
                )}
              </span>
            }
          />
          <LicenseInfoRow
            label={t("lastVerified")}
            value={status.lastVerified ? formatDate(status.lastVerified) : t("never")}
          />
          {status.gracePeriodEnd && (
            <LicenseInfoRow label={t("gracePeriodEnd")} value={formatDate(status.gracePeriodEnd)} />
          )}
        </>
      )}

      {instanceId && (
        <>
          <LicenseInfoRow
            label={t("instanceId")}
            value={
              <span className="flex items-center gap-2">
                <code className="text-xs">{instanceId}</code>
                <CopyButton className="text-xs text-muted-foreground hover:text-foreground" value={instanceId}>
                  {t("copy")}
                </CopyButton>
              </span>
            }
          />
          <LicenseInfoRow
            label={t("instanceIdSource")}
            value={isInstanceIdFromEnv() ? t("instanceIdFromEnv") : t("instanceIdAutoGenerated")}
          />
        </>
      )}

      {!isCloud && status.mode === "community" && (
        <p className="mt-4 text-sm text-muted-foreground">
          {status.reason === "invalid" ? t("invalidLicenseKey") : t("noLicenseKey")}
        </p>
      )}
    </div>
  );
};
