-- AlterEnum
ALTER TYPE "AuditAction" ADD VALUE 'PASSWORD_SET';
ALTER TYPE "AuditAction" ADD VALUE 'PASSWORD_CHANGE';
ALTER TYPE "AuditAction" ADD VALUE 'PASSWORD_RESET_REQUEST';
ALTER TYPE "AuditAction" ADD VALUE 'PASSWORD_RESET_COMPLETE';

-- AlterTable
ALTER TABLE "User" ADD COLUMN     "passwordHash" TEXT;
