name: Build

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [dev]

permissions:
  contents: read

concurrency:
  cancel-in-progress: true
  group: build-${{ github.ref }}

jobs:
  changes:
    name: Detect changes
    runs-on: ubuntu-latest
    outputs:
      should-build: ${{ steps.filter.outputs.should-build }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36 # v3
        id: filter
        with:
          filters: .github/filters.yml

  build:
    name: Build and export
    needs: [changes]
    if: >-
      github.event_name == 'push' ||
      needs.changes.outputs.should-build == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Cache Turbo
        uses: actions/cache@v4
        with:
          path: .turbo
          key: turbo-build-${{ runner.os }}-${{ github.sha }}
          restore-keys: |
            turbo-build-${{ runner.os }}-
      - name: Build and export
        env:
          ESPACE_MEMBRE_API_KEY: fakesecret
        run: pnpm build
