name: Lint

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [dev]

permissions:
  contents: read

concurrency:
  cancel-in-progress: true
  group: lint-${{ github.ref }}

jobs:
  changes:
    name: Detect changes
    runs-on: ubuntu-latest
    outputs:
      should-lint: ${{ steps.filter.outputs.should-lint }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36 # v3
        id: filter
        with:
          filters: .github/filters.yml

  code:
    name: Lint
    needs: [changes]
    if: >-
      github.event_name == 'push' ||
      needs.changes.outputs.should-lint == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: "pnpm"
      - name: Unlock git-crypt
        run: |
          sudo apt-get install -y git-crypt
          echo "$GIT_CRYPT_KEY" | base64 -d | git-crypt unlock -
        env:
          GIT_CRYPT_KEY: ${{ secrets.GIT_CRYPT_KEY }}
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Cache Turbo
        uses: actions/cache@v4
        with:
          path: .turbo
          key: turbo-lint-${{ runner.os }}-${{ github.sha }}
          restore-keys: |
            turbo-lint-${{ runner.os }}-
      - run: pnpm --filter @roadmaps-faciles/web exec -- prisma generate
      - name: Lint
        run: pnpm lint
        env:
          NODE_OPTIONS: "--max-old-space-size=4096"
